name: Publish Package
description: 'Publish the package to crates.io'
inputs:
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true

runs:
  using: composite
  steps:
    - name: Publish Library
      shell: bash
      if: ${{ inputs.dry_run == 'false' }}
      run: cargo publish -p eventsource-client
