name: CI Workflow
description: 'Shared CI workflow.'

inputs:
  feature-flags:
    description: 'Cargo feature flags to pass to test and clippy commands'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Check formatting
      shell: bash
      run: cargo fmt --check

    - name: Run tests
      shell: bash
      run: cargo test ${{ inputs.feature-flags }} -p eventsource-client

    - name: Run slower integration tests
      shell: bash
      run: cargo test ${{ inputs.feature-flags }} -p eventsource-client --lib -- --ignored

    - name: Run clippy checks
      shell: bash
      run: cargo clippy ${{ inputs.feature-flags }} -p eventsource-client -- -D warnings

    - name: Build contract tests
      shell: bash
      run: make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: make start-contract-test-service-bg

    - name: Run contract tests
      shell: bash
      run: make run-contract-tests
